language: none_js
none_js: 
 - "8.11"


branches:
  only:
    -travis
addons:
    chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules
  script:
    - ng build --prod
  deploy:
    provider: pages
    skip-clenaup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: ./dist/
    on: